version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.13"

sphinx:
  configuration: Docs/Source/conf.py 

python:
  install:
    - method: pip
      path: .
    - requirements: Docs/requirements.txt