[tox]
envlist = py3{10-13}
isolated_build = true
requires =
    tox-conda

[testenv]
setenv =
    CONDA_DLL_SEARCH_MODIFICATION_ENABLE = 1

conda_channels =
    conda-forge

conda_deps =
    pip
    pytest
    rdkit
    scikit-learn
    matplotlib
    mdtraj
    pytest-cov
    tqdm

commands =
    pip install .
    pytest
